
version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    image: selimhorri/service-discovery-ecommerce-boot:0.1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/

  cloud-config-container:
    image: selimhorri/cloud-config-ecommerce-boot:0.1.0
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME: "cloud-config-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"

  api-gateway-container:
    image: selimhorri/api-gateway-ecommerce-boot:0.1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "api-gateway-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  proxy-client-container:
    image: selimhorri/proxy-client-ecommerce-boot:0.1.0
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "proxy-client-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  order-service-container:
    image: selimhorri/order-service-ecommerce-boot:0.1.0
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "order-service-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  payment-service-container:
    image: selimhorri/payment-service-ecommerce-boot:0.1.0
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "payment-service-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  product-service-container:
    image: selimhorri/product-service-ecommerce-boot:0.1.0
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "product-service-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  shipping-service-container:
    image: selimhorri/shipping-service-ecommerce-boot:0.1.0
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "shipping-service-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  user-service-container:
    image: selimhorri/user-service-ecommerce-boot:0.1.0
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "user-service-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  favourite-service-container:
    image: selimhorri/favourite-service-ecommerce-boot:0.1.0
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discoverycontainer:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discoverycontainer:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
      - EUREKA_INSTANCE_HOSTNAME: "favourite-service-container"
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"



