apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-container
  name: zipkin-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin-container
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/ecommerce-microservices-k8s-default: "true"
        io.kompose.service: zipkin-container
    spec:
      containers:
        - image: openzipkin/zipkin
          name: zipkin-container
          ports:
            - containerPort: 9411
              hostPort: 9411
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
